[build]
  command = "npm run build"
  publish = "dist"
  environment = { SECRETS_SCAN_OMIT_KEYS = "VITE_KAKAO_MAP_API_KEY" }

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/guestbook"
  to = "/.netlify/functions/get-guestbook"
  status = 200
  method = "GET"

[[redirects]]
  from = "/api/guestbook"
  to = "/.netlify/functions/post-guestbook"
  status = 200
  method = "POST"

[[redirects]]
  from = "/api/rsvp"
  to = "/.netlify/functions/post-rsvp"
  status = 200
  method = "POST"
